### ISSUE TITLE
/usr/lib/python3.10/site-packages/PyQt5/bindings/QtCore/QtCoremod.sip:23: syntax error

### ISSUE THREAD

**Issue by AladW** [ros-noetic-arch/ros-noetic-python-qt-binding#8]
```
==> Making package: ros-noetic-qt-gui-cpp 0.4.2-2 (Tue 22 Feb 2022 05:14:26 PM CET)
==> Checking runtime dependencies...
==> Installing missing dependencies...
resolving dependencies...
looking for conflicting packages...

Package (42)                          New Version  Net Change  Download Size

alad/console-bridge                   1.0.1-2        0.04 MiB               
community/gtest                       1.11.0-3       2.29 MiB               
extra/mariadb-libs                    10.6.5-2      23.19 MiB               
community/poco                        1.11.1-1      17.57 MiB               
alad/python-catkin_pkg                0.4.24-2       0.51 MiB               
community/python-distro               1.6.0-4        0.15 MiB               
community/python-empy                 3.3.4-7        0.31 MiB               
extra/python-nose                     1.3.7-14       0.89 MiB               
alad/python-rosdep                    0.21.0-1       0.67 MiB               
alad/python-rosdistro                 0.8.3-1        0.49 MiB               
alad/python-rospkg                    1.3.0-1        0.28 MiB               
community/python-toml                 0.10.2-7       0.14 MiB               
community/python-yaml                 5.4.1.1-4      0.74 MiB               
alad/ros-build-tools                  0.3.2-2        0.00 MiB               
alad/ros-noetic-catkin                0.8.10-1       0.51 MiB               
alad/ros-noetic-class-loader          0.5.0-2        0.24 MiB               
alad/ros-noetic-cpp-common            0.7.2-1        0.08 MiB               
alad/ros-noetic-gencpp                0.6.5-1        0.04 MiB               
alad/ros-noetic-geneus                3.0.0-1        0.08 MiB               
alad/ros-noetic-genlisp               0.4.18-2       0.08 MiB               
alad/ros-noetic-genmsg                0.5.16-2       0.14 MiB               
alad/ros-noetic-gennodejs             2.0.1-1        0.08 MiB               
alad/ros-noetic-genpy                 0.6.15-1       0.20 MiB               
alad/ros-noetic-message-generation    0.4.1-2        0.01 MiB               
alad/ros-noetic-message-runtime       0.4.13-1       0.01 MiB               
alad/ros-noetic-python-qt-binding     0.4.4-1        0.05 MiB               
alad/ros-noetic-ros-environment       1.3.2-1        0.01 MiB               
alad/ros-noetic-rosbuild              1.15.8-1       0.11 MiB               
alad/ros-noetic-rosconsole            1.14.3-5       0.58 MiB               
alad/ros-noetic-roscpp-serialization  0.7.2-1        0.05 MiB               
alad/ros-noetic-roscpp-traits         0.7.2-1        0.04 MiB               
alad/ros-noetic-roslib                1.15.8-1       0.39 MiB               
alad/ros-noetic-rospack               2.6.2-1        0.36 MiB               
alad/ros-noetic-rostime               0.7.2-1        0.16 MiB               
alad/tango-icon-theme                 0.8.90-14     30.87 MiB               
core/unixodbc                         2.3.9-1        0.89 MiB               
extra/python-sip4                     4.19.25-3      0.24 MiB               
alad/ros-noetic-pluginlib             1.13.0-1       0.08 MiB               
alad/ros-noetic-qt-gui                0.4.2-1        0.44 MiB               
extra/sip                             6.5.0-2        1.79 MiB       0.32 MiB
extra/sip4                            4.19.25-3      0.48 MiB               
community/tinyxml                     2.6.2-8        0.18 MiB               

Total Download Size:    0.32 MiB
Total Installed Size:  85.46 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 sip-6.5.0-2-x86_64    326.6 KiB  2.28 MiB/s 00:00 [######################] 100%
(42/42) checking keys in keyring                   [######################] 100%
(42/42) checking package integrity                 [######################] 100%
(42/42) loading package files                      [######################] 100%
(42/42) checking for file conflicts                [######################] 100%
(42/42) checking available disk space              [######################] 100%
:: Processing package changes...
( 1/42) installing console-bridge                  [######################] 100%
( 2/42) installing mariadb-libs                    [######################] 100%
Optional dependencies for mariadb-libs
    krb5: for gssapi authentication [installed]
( 3/42) installing unixodbc                        [######################] 100%
( 4/42) installing poco                            [######################] 100%
( 5/42) installing ros-noetic-class-loader         [######################] 100%
( 6/42) installing ros-noetic-cpp-common           [######################] 100%
( 7/42) installing ros-noetic-rostime              [######################] 100%
( 8/42) installing ros-noetic-roscpp-traits        [######################] 100%
( 9/42) installing python-nose                     [######################] 100%
(10/42) installing gtest                           [######################] 100%
Optional dependencies for gtest
    python: gmock generator [installed]
(11/42) installing python-catkin_pkg               [######################] 100%
(12/42) installing python-empy                     [######################] 100%
(13/42) installing ros-build-tools                 [######################] 100%
(14/42) installing ros-noetic-catkin               [######################] 100%
(15/42) installing ros-noetic-genmsg               [######################] 100%
(16/42) installing python-yaml                     [######################] 100%
(17/42) installing ros-noetic-genpy                [######################] 100%
(18/42) installing ros-noetic-roscpp-serialization [######################] 100%
(19/42) installing ros-noetic-message-runtime      [######################] 100%
(20/42) installing ros-noetic-geneus               [######################] 100%
(21/42) installing ros-noetic-gencpp               [######################] 100%
(22/42) installing ros-noetic-gennodejs            [######################] 100%
(23/42) installing ros-noetic-genlisp              [######################] 100%
(24/42) installing ros-noetic-message-generation   [######################] 100%
(25/42) installing ros-noetic-rosbuild             [######################] 100%
(26/42) installing ros-noetic-rosconsole           [######################] 100%
Optional dependencies for ros-noetic-rosconsole
    google-glog: glog backend [installed]
(27/42) installing ros-noetic-ros-environment      [######################] 100%
(28/42) installing python-distro                   [######################] 100%
(29/42) installing python-rospkg                   [######################] 100%
(30/42) installing python-rosdistro                [######################] 100%
(31/42) installing python-rosdep                   [######################] 100%
(32/42) installing ros-noetic-rospack              [######################] 100%
(33/42) installing ros-noetic-roslib               [######################] 100%
(34/42) installing ros-noetic-pluginlib            [######################] 100%
(35/42) installing ros-noetic-python-qt-binding    [######################] 100%
(36/42) installing tango-icon-theme                [######################] 100%
(37/42) installing ros-noetic-qt-gui               [######################] 100%
(38/42) installing tinyxml                         [######################] 100%
(39/42) installing python-toml                     [######################] 100%
(40/42) installing sip                             [######################] 100%
(41/42) installing python-sip4                     [######################] 100%
(42/42) installing sip4                            [######################] 100%
:: Running post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Updating icon theme caches...
==> Checking buildtime dependencies...
==> Installing missing dependencies...
resolving dependencies...
looking for conflicting packages...

Package (1)                    New Version  Net Change

alad/ros-noetic-cmake-modules  0.5.0-1        0.06 MiB

Total Installed Size:  0.06 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                     [######################] 100%
(1/1) checking package integrity                   [######################] 100%
(1/1) loading package files                        [######################] 100%
(1/1) checking for file conflicts                  [######################] 100%
(1/1) checking available disk space                [######################] 100%
:: Processing package changes...
(1/1) installing ros-noetic-cmake-modules          [######################] 100%
==> Retrieving sources...
  -> Downloading ros-noetic-qt-gui-cpp-0.4.2.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   146  100   146    0     0   2705      0 --:--:-- --:--:-- --:--:--  2754
100 97267    0 97267    0     0   342k      0 --:--:-- --:--:-- --:--:-- 4104k
==> Validating source files with sha256sums...
    ros-noetic-qt-gui-cpp-0.4.2.tar.gz ... Passed
==> Extracting sources...
  -> Extracting ros-noetic-qt-gui-cpp-0.4.2.tar.gz with bsdtar
==> Starting build()...
-- The C compiler identification is GNU 11.1.0
-- The CXX compiler identification is GNU 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /home/archie/.cache/aurutils/sync/ros-noetic-qt-gui-cpp/src/build/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/noetic
-- This workspace overlays: /opt/ros/noetic
-- Found PythonInterp: /usr/bin/python (found suitable version "3.10.2", minimum required is "3") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using default Python package layout
-- Found PY_em: /usr/lib/python3.10/site-packages/em.py  
-- Using empy: /usr/lib/python3.10/site-packages/em.py
-- Using CATKIN_ENABLE_TESTING: ON
-- Skip enable_testing() when building binary package
-- Using CATKIN_TEST_RESULTS_DIR: /home/archie/.cache/aurutils/sync/ros-noetic-qt-gui-cpp/src/build/test_results
-- Forcing gtest/gmock from source, though one was otherwise available.
-- Found gtest sources under '/usr/src/gmock': gtests will be built
-- Found gmock sources under '/usr/src/gmock': gmock will be built
-- Found Python: /usr/bin/python3.10 (found version "3.10.2") found components: Interpreter 
-- Found Threads: TRUE  
-- Using Python nosetests: /usr/bin/nosetests-3.10
-- catkin 0.8.10
-- BUILD_SHARED_LIBS is on
-- Found Boost: /usr/lib64/cmake/Boost-1.78.0/BoostConfig.cmake (found version "1.78.0") found components: filesystem system 
-- Found TinyXML: /usr/lib/libtinyxml.so  
/opt/ros/noetic/share/catkin/cmake/interrogate_setup_dot_py.py:43: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.core
-- Found PythonLibs: /usr/lib/libpython3.10.so (found suitable version "3.10.2", minimum required is "3.10") 
-- Shiboken binding generator NOT available.
-- Found PythonInterp: /usr/bin/python (found suitable version "3.10.2", minimum required is "3.10") 
-- SIP binding generator available at: /usr/bin/sip
-- Python binding generators: sip
-- Configuring done
-- Generating done
-- Build files have been written to: /home/archie/.cache/aurutils/sync/ros-noetic-qt-gui-cpp/src/build
[ 10%] Generating __/__/include/qt_gui_cpp/moc_plugin_context.cpp
[ 10%] Generating __/__/include/qt_gui_cpp/moc_plugin.cpp
[ 15%] Generating __/__/include/qt_gui_cpp/moc_plugin_bridge.cpp
[ 26%] Building CXX object src/qt_gui_cpp/CMakeFiles/qt_gui_cpp.dir/composite_plugin_provider.cpp.o
[ 26%] Building CXX object src/qt_gui_cpp/CMakeFiles/qt_gui_cpp.dir/generic_proxy.cpp.o
[ 31%] Building CXX object src/qt_gui_cpp/CMakeFiles/qt_gui_cpp.dir/plugin_bridge.cpp.o
[ 36%] Building CXX object src/qt_gui_cpp/CMakeFiles/qt_gui_cpp.dir/plugin_context.cpp.o
[ 42%] Building CXX object src/qt_gui_cpp/CMakeFiles/qt_gui_cpp.dir/plugin_provider.cpp.o
[ 47%] Building CXX object src/qt_gui_cpp/CMakeFiles/qt_gui_cpp.dir/plugin_descriptor.cpp.o
[ 52%] Building CXX object src/qt_gui_cpp/CMakeFiles/qt_gui_cpp.dir/recursive_plugin_provider.cpp.o
/home/archie/.cache/aurutils/sync/ros-noetic-qt-gui-cpp/src/qt_gui_core-0.4.2/qt_gui_cpp/src/qt_gui_cpp/plugin_provider.cpp: In member function ‘virtual QMap<QString, QString> qt_gui_cpp::PluginProvider::discover(QObject*)’:
/home/archie/.cache/aurutils/sync/ros-noetic-qt-gui-cpp/src/qt_gui_core-0.4.2/qt_gui_cpp/src/qt_gui_cpp/plugin_provider.cpp:52:18: warning: ‘QMap<K, V>& QMap<K, V>::unite(const QMap<K, V>&) [with Key = QString; T = QString]’ is deprecated: Use QMultiMap for maps storing multiple values with the same key. [-Wdeprecated-declarations]
   52 |     plugins.unite(plugin);
      |     ~~~~~~~~~~~~~^~~~~~~~
In file included from /usr/include/qt/QtCore/QMap:1,
                 from /home/archie/.cache/aurutils/sync/ros-noetic-qt-gui-cpp/src/qt_gui_core-0.4.2/qt_gui_cpp/include/qt_gui_cpp/plugin_context.h:39,
                 from /home/archie/.cache/aurutils/sync/ros-noetic-qt-gui-cpp/src/qt_gui_core-0.4.2/qt_gui_cpp/include/qt_gui_cpp/plugin.h:37,
                 from /home/archie/.cache/aurutils/sync/ros-noetic-qt-gui-cpp/src/qt_gui_core-0.4.2/qt_gui_cpp/include/qt_gui_cpp/plugin_provider.h:36,
                 from /home/archie/.cache/aurutils/sync/ros-noetic-qt-gui-cpp/src/qt_gui_core-0.4.2/qt_gui_cpp/src/qt_gui_cpp/plugin_provider.cpp:33:
/usr/include/qt/QtCore/qmap.h:1378:15: note: declared here
 1378 | QMap<Key, T> &QMap<Key, T>::unite(const QMap<Key, T> &other)
      |               ^~~~~~~~~~~~
[ 57%] Building CXX object src/qt_gui_cpp/CMakeFiles/qt_gui_cpp.dir/ros_pluginlib_plugin_provider.cpp.o
[ 63%] Building CXX object src/qt_gui_cpp/CMakeFiles/qt_gui_cpp.dir/settings.cpp.o
[ 68%] Building CXX object src/qt_gui_cpp/CMakeFiles/qt_gui_cpp.dir/__/__/include/qt_gui_cpp/moc_plugin.cpp.o
[ 73%] Building CXX object src/qt_gui_cpp/CMakeFiles/qt_gui_cpp.dir/__/__/include/qt_gui_cpp/moc_plugin_bridge.cpp.o
[ 78%] Building CXX object src/qt_gui_cpp/CMakeFiles/qt_gui_cpp.dir/__/__/include/qt_gui_cpp/moc_plugin_context.cpp.o
In file included from /usr/include/boost/smart_ptr/detail/sp_thread_sleep.hpp:2,
                 from /usr/include/boost/smart_ptr/detail/yield_k.hpp:23,
                 from /usr/include/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp:14,
                 from /usr/include/boost/smart_ptr/detail/spinlock.hpp:42,
                 from /usr/include/boost/smart_ptr/detail/spinlock_pool.hpp:25,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:29,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /usr/include/boost/date_time/time_clock.hpp:17,
                 from /usr/include/boost/thread/thread_time.hpp:9,
                 from /usr/include/boost/thread/lock_types.hpp:18,
                 from /usr/include/boost/thread/pthread/thread_data.hpp:12,
                 from /usr/include/boost/thread/thread_only.hpp:17,
                 from /usr/include/boost/thread/thread.hpp:12,
                 from /usr/include/boost/thread.hpp:13,
                 from /opt/ros/noetic/include/class_loader/multi_library_class_loader.hpp:35,
                 from /opt/ros/noetic/include/pluginlib/class_loader.hpp:38,
                 from /home/archie/.cache/aurutils/sync/ros-noetic-qt-gui-cpp/src/qt_gui_core-0.4.2/qt_gui_cpp/include/qt_gui_cpp/ros_pluginlib_plugin_provider.h:45,
                 from /home/archie/.cache/aurutils/sync/ros-noetic-qt-gui-cpp/src/qt_gui_core-0.4.2/qt_gui_cpp/include/qt_gui_cpp/ros_pluginlib_plugin_provider_for_plugin_providers.h:37,
                 from /home/archie/.cache/aurutils/sync/ros-noetic-qt-gui-cpp/src/qt_gui_core-0.4.2/qt_gui_cpp/include/qt_gui_cpp/recursive_plugin_provider.h:3,
                 from /home/archie/.cache/aurutils/sync/ros-noetic-qt-gui-cpp/src/qt_gui_core-0.4.2/qt_gui_cpp/src/qt_gui_cpp/recursive_plugin_provider.cpp:33:
/usr/include/boost/bind.hpp:36:1: note: ‘#pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.’
   36 | BOOST_PRAGMA_MESSAGE(
      | ^~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/boost/smart_ptr/detail/sp_thread_sleep.hpp:2,
                 from /usr/include/boost/smart_ptr/detail/yield_k.hpp:23,
                 from /usr/include/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp:14,
                 from /usr/include/boost/smart_ptr/detail/spinlock.hpp:42,
                 from /usr/include/boost/smart_ptr/detail/spinlock_pool.hpp:25,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:29,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /usr/include/boost/date_time/time_clock.hpp:17,
                 from /usr/include/boost/thread/thread_time.hpp:9,
                 from /usr/include/boost/thread/lock_types.hpp:18,
                 from /usr/include/boost/thread/pthread/thread_data.hpp:12,
                 from /usr/include/boost/thread/thread_only.hpp:17,
                 from /usr/include/boost/thread/thread.hpp:12,
                 from /usr/include/boost/thread.hpp:13,
                 from /opt/ros/noetic/include/class_loader/multi_library_class_loader.hpp:35,
                 from /opt/ros/noetic/include/pluginlib/class_loader.hpp:38,
                 from /home/archie/.cache/aurutils/sync/ros-noetic-qt-gui-cpp/src/qt_gui_core-0.4.2/qt_gui_cpp/include/qt_gui_cpp/ros_pluginlib_plugin_provider.h:45,
                 from /home/archie/.cache/aurutils/sync/ros-noetic-qt-gui-cpp/src/qt_gui_core-0.4.2/qt_gui_cpp/src/qt_gui_cpp/ros_pluginlib_plugin_provider.cpp:34:
/usr/include/boost/bind.hpp:36:1: note: ‘#pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.’
   36 | BOOST_PRAGMA_MESSAGE(
      | ^~~~~~~~~~~~~~~~~~~~
[ 84%] Linking CXX shared library ../../devel/lib/libqt_gui_cpp.so
[ 84%] Built target qt_gui_cpp
[ 89%] Running SIP generator for qt_gui_cpp_sip Python bindings...
/opt/ros/noetic/share/python_qt_binding/cmake/sip_configure.py:2: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.spawn import find_executable
sip: Deprecation warning: qt_gui_cpp.sip:1: %Module version number should be specified using the 'version' argument
sip: /usr/lib/python3.10/site-packages/PyQt5/bindings/QtCore/QtCoremod.sip:23: syntax error
Traceback (most recent call last):
  File "/opt/ros/noetic/share/python_qt_binding/cmake/sip_configure.py", line 122, in <module>
    subprocess.check_call(cmd)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/sip', '-c', '/home/archie/.cache/aurutils/sync/ros-noetic-qt-gui-cpp/src/build/sip/qt_gui_cpp_sip', '-b', '/home/archie/.cache/aurutils/sync/ros-noetic-qt-gui-cpp/src/build/sip/qt_gui_cpp_sip/pyqtscripting.sbf', '-I', '/usr/lib/python3.10/site-packages/PyQt5/bindings', '-w', '-n', 'PyQt5.sip', '-t', 'Qt_5_15_0', '-t', 'WS_X11', 'qt_gui_cpp.sip']' returned non-zero exit status 1.
make[2]: *** [src/qt_gui_cpp_sip/CMakeFiles/libqt_gui_cpp_sip.dir/build.make:103: sip/qt_gui_cpp_sip/Makefile] Error 1
make[1]: *** [CMakeFiles/Makefile2:478: src/qt_gui_cpp_sip/CMakeFiles/libqt_gui_cpp_sip.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by acxz** [comment]
Thx for the report.

See: ros-noetic-arch/ros-noetic-python-qt-binding#7

Closing due to dup of above issue
